[project]
name = "hr-ai-assistent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-jose[cryptography]>=3.5.0",
]
