"""removed the embedding table and updated the usercv table

Revision ID: 0aea4a775c5f
Revises: 49672592722a
Create Date: 2025-10-21 12:43:08.991397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '0aea4a775c5f'
down_revision: Union[str, Sequence[str], None] = '49672592722a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_embeddings_id'), table_name='cv_embeddings')
    op.drop_table('cv_embeddings')
    op.add_column('user_cvs', sa.Column('cv_embeddings', Vector(dim=384), nullable=True))
    op.drop_column('user_cvs', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cvs', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_cvs', 'cv_embeddings')
    op.create_table('cv_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_Title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cv_embeddings', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cv_embeddings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cv_embeddings_pkey'))
    )
    op.create_index(op.f('ix_cv_embeddings_id'), 'cv_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###
