"""incressed vector dimension 384

Revision ID: 0b16ceed48eb
Revises: 215a1c27c70e
Create Date: 2025-10-23 11:23:40.864694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '0b16ceed48eb'
down_revision: Union[str, Sequence[str], None] = '215a1c27c70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cv_chunks', 'embedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=384),
               existing_nullable=True)
    op.alter_column('user_cvs', 'cv_embeddings',
               existing_type=Vector(dim=768),
               type_=Vector(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cvs', 'cv_embeddings',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.alter_column('user_cv_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###
