"""adding table userscvchunk

Revision ID: 0c92edeac59e
Revises: 0aea4a775c5f
Create Date: 2025-10-21 15:59:55.116817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '0c92edeac59e'
down_revision: Union[str, Sequence[str], None] = '0aea4a775c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cv_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['user_cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cv_chunks_id'), 'user_cv_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cv_chunks_id'), table_name='user_cv_chunks')
    op.drop_table('user_cv_chunks')
    # ### end Alembic commands ###
