"""added ondelete CASCADE

Revision ID: 1106e31641e8
Revises: 1b3e7956c020
Create Date: 2025-10-13 13:20:32.843152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1106e31641e8'
down_revision: Union[str, Sequence[str], None] = '1b3e7956c020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('referrals_user_id_fkey'), 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key(op.f('referrals_user_id_fkey'), 'referrals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
