"""incressed vector dimension 768

Revision ID: 215a1c27c70e
Revises: 272c89a96e13
Create Date: 2025-10-22 16:25:53.164970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '215a1c27c70e'
down_revision: Union[str, Sequence[str], None] = '272c89a96e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cv_chunks', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=768),
               existing_nullable=True)
    op.alter_column('user_cvs', 'cv_embeddings',
               existing_type=Vector(dim=384),
               type_=Vector(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cvs', 'cv_embeddings',
               existing_type=Vector(dim=768),
               type_=Vector(dim=384),
               existing_nullable=True)
    op.alter_column('user_cv_chunks', 'embedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###
