"""added  a table to link users and referal codes

Revision ID: 256439b0f383
Revises: ce13b2ca79a2
Create Date: 2025-10-14 10:16:05.703199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256439b0f383'
down_revision: Union[str, Sequence[str], None] = 'ce13b2ca79a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_links_id'), 'referral_links', ['id'], unique=False)
    op.add_column('referrals', sa.Column('referral_code', sa.String(), nullable=False))
    op.drop_column('referrals', 'referal_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referal_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('referrals', 'referral_code')
    op.drop_index(op.f('ix_referral_links_id'), table_name='referral_links')
    op.drop_table('referral_links')
    # ### end Alembic commands ###
