"""added a column downloaded

Revision ID: 2ec0b9150b36
Revises: 256439b0f383
Create Date: 2025-10-16 08:23:28.279231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec0b9150b36'
down_revision: Union[str, Sequence[str], None] = '256439b0f383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_processed', sa.Column('downloaded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_processed', 'downloaded')
    # ### end Alembic commands ###
