"""added an embending table with extensions

Revision ID: 49672592722a
Revises: 2ec0b9150b36
Create Date: 2025-10-18 13:12:05.474955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '49672592722a'
down_revision: Union[str, Sequence[str], None] = '2ec0b9150b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_Title', sa.String(), nullable=False),
    sa.Column('cv_embeddings', Vector(dim=384), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_embeddings_id'), 'cv_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_embeddings_id'), table_name='cv_embeddings')
    op.drop_table('cv_embeddings')
    # ### end Alembic commands ###
