"""added a column in the CVToprocess table

Revision ID: 70de777c60d7
Revises: 3b8ddf500391
Create Date: 2025-10-03 15:07:53.531683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70de777c60d7'
down_revision: Union[str, Sequence[str], None] = '3b8ddf500391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_processed', sa.Column('cv_to_process_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cv_processed', 'cv_to_process', ['cv_to_process_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cv_processed', type_='foreignkey')
    op.drop_column('cv_processed', 'cv_to_process_id')
    # ### end Alembic commands ###
