"""added ondelete CASCADE

Revision ID: 916681263189
Revises: 1106e31641e8
Create Date: 2025-10-13 15:19:58.686795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916681263189'
down_revision: Union[str, Sequence[str], None] = '1106e31641e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('credits_user_id_fkey'), 'credits', type_='foreignkey')
    op.create_foreign_key(None, 'credits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credits', type_='foreignkey')
    op.create_foreign_key(op.f('credits_user_id_fkey'), 'credits', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
