"""store new tables with with new Vector size 

Revision ID: bae808b5a682
Revises: e6fd90a2ed01
Create Date: 2025-10-23 12:31:42.279578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'bae808b5a682'
down_revision: Union[str, Sequence[str], None] = 'e6fd90a2ed01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cv_chunks', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=768),
               existing_nullable=True)
    op.alter_column('user_cvs', 'cv_embeddings',
               existing_type=Vector(dim=384),
               type_=Vector(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cvs', 'cv_embeddings',
               existing_type=Vector(dim=768),
               type_=Vector(dim=384),
               existing_nullable=True)
    op.alter_column('user_cv_chunks', 'embedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###
