"""removed referred_user_id

Revision ID: ce13b2ca79a2
Revises: ebd04620c776
Create Date: 2025-10-14 09:54:38.811009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce13b2ca79a2'
down_revision: Union[str, Sequence[str], None] = 'ebd04620c776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('referrals_referred_user_id_fkey'), 'referrals', type_='foreignkey')
    op.drop_column('referrals', 'referred_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referred_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('referrals_referred_user_id_fkey'), 'referrals', 'users', ['referred_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
