"""store new tables

Revision ID: e6fd90a2ed01
Revises: 0b16ceed48eb
Create Date: 2025-10-23 11:55:16.339250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e6fd90a2ed01'
down_revision: Union[str, Sequence[str], None] = '0b16ceed48eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('cv_embeddings', Vector(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cvs_id'), 'user_cvs', ['id'], unique=False)
    op.create_table('user_cv_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['user_cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cv_chunks_id'), 'user_cv_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cv_chunks_id'), table_name='user_cv_chunks')
    op.drop_table('user_cv_chunks')
    op.drop_index(op.f('ix_user_cvs_id'), table_name='user_cvs')
    op.drop_table('user_cvs')
    # ### end Alembic commands ###
