"""adding referred user id

Revision ID: ebd04620c776
Revises: 916681263189
Create Date: 2025-10-14 09:12:19.102339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd04620c776'
down_revision: Union[str, Sequence[str], None] = '916681263189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referred_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'referrals', 'users', ['referred_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_column('referrals', 'referred_user_id')
    # ### end Alembic commands ###
