"""added filename in the cvembenddings table

Revision ID: ed10062e7370
Revises: 0c92edeac59e
Create Date: 2025-10-22 11:31:37.158654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed10062e7370'
down_revision: Union[str, Sequence[str], None] = '0c92edeac59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cvs', sa.Column('file_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_cvs', 'file_name')
    # ### end Alembic commands ###
